{% set version = "3.1.0" %}

package:
  name: jsonfield
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonfield/jsonfield-{{ version }}.tar.gz
  sha256: 7e4e84597de21eeaeeaaa7cc5da08c61c48a9b64d0c446b2d71255d01812887a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.11
    - six

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jsonfield

about:
  home: https://github.com/dmkoch/django-jsonfield/
  license: MIT
  license_file: LICENSE
  summary: 'A reusable Django field that allows you to store validated JSON in your model.'
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
